#ifndef MRUBY_ZLib_FUNCTIONS_HEADER
#define MRUBY_ZLib_FUNCTIONS_HEADER

#define BIND_adler32_FUNCTION TRUE
#define BIND_adler32_combine_FUNCTION TRUE
#define BIND_compress_FUNCTION TRUE
#define BIND_compress2_FUNCTION TRUE
#define BIND_compressBound_FUNCTION TRUE
#define BIND_crc32_FUNCTION TRUE
#define BIND_crc32_combine_FUNCTION TRUE
#define BIND_deflate_FUNCTION TRUE
#define BIND_deflateBound_FUNCTION TRUE
#define BIND_deflateCopy_FUNCTION TRUE
#define BIND_deflateEnd_FUNCTION TRUE
#define BIND_deflateInit_FUNCTION TRUE
#define BIND_deflateInit2_FUNCTION TRUE
#define BIND_deflateParams_FUNCTION TRUE
#define BIND_deflatePrime_FUNCTION TRUE
#define BIND_deflateReset_FUNCTION TRUE
#define BIND_deflateResetKeep_FUNCTION TRUE
#define BIND_deflateSetDictionary_FUNCTION FALSE
#define BIND_deflateSetHeader_FUNCTION TRUE
#define BIND_deflateTune_FUNCTION TRUE
#define BIND_get_crc_table_FUNCTION FALSE
#define BIND_gzbuffer_FUNCTION TRUE
#define BIND_gzclearerr_FUNCTION TRUE
#define BIND_gzclose_FUNCTION TRUE
#define BIND_gzdirect_FUNCTION TRUE
#define BIND_gzdopen_FUNCTION TRUE
#define BIND_gzeof_FUNCTION TRUE
#define BIND_gzerror_FUNCTION TRUE
#define BIND_gzflush_FUNCTION TRUE
#define BIND_gzgetc_FUNCTION TRUE
#define BIND_gzgets_FUNCTION TRUE
#define BIND_gzoffset_FUNCTION TRUE
#define BIND_gzopen_FUNCTION TRUE
#define BIND_gzputc_FUNCTION TRUE
#define BIND_gzputs_FUNCTION TRUE
#define BIND_gzread_FUNCTION TRUE
#define BIND_gzrewind_FUNCTION TRUE
#define BIND_gzseek_FUNCTION TRUE
#define BIND_gzsetparams_FUNCTION TRUE
#define BIND_gztell_FUNCTION TRUE
#define BIND_gzungetc_FUNCTION TRUE
#define BIND_gzwrite_FUNCTION TRUE
#define BIND_inflate_FUNCTION TRUE
#define BIND_inflateBack_FUNCTION FALSE
#define BIND_inflateBackEnd_FUNCTION TRUE
#define BIND_inflateCopy_FUNCTION TRUE
#define BIND_inflateEnd_FUNCTION TRUE
#define BIND_inflateGetDictionary_FUNCTION FALSE
#define BIND_inflateGetHeader_FUNCTION TRUE
#define BIND_inflateInit_FUNCTION TRUE
#define BIND_inflateInit2_FUNCTION TRUE
#define BIND_inflateMark_FUNCTION TRUE
#define BIND_inflatePrime_FUNCTION TRUE
#define BIND_inflateReset_FUNCTION TRUE
#define BIND_inflateReset2_FUNCTION TRUE
#define BIND_inflateResetKeep_FUNCTION TRUE
#define BIND_inflateSetDictionary_FUNCTION FALSE
#define BIND_inflateSync_FUNCTION TRUE
#define BIND_inflateSyncPoint_FUNCTION TRUE
#define BIND_inflateUndermine_FUNCTION TRUE
#define BIND_uncompress_FUNCTION TRUE
#define BIND_zError_FUNCTION TRUE
#define BIND_zlibCompileFlags_FUNCTION TRUE
#define BIND_zlibVersion_FUNCTION TRUE
#endif
